// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHvak7fv75OzfdvYGAGfW4K8nXFkP-240',
    appId: '1:811849908533:web:7ea3845e446c6b64a88c7c',
    messagingSenderId: '811849908533',
    projectId: 'imageupload-cb863',
    authDomain: 'imageupload-cb863.firebaseapp.com',
    storageBucket: 'imageupload-cb863.appspot.com',
    measurementId: 'G-HNF38MD1VS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_IHMyQkSZCSYWTSvorOubrU3wnNxtOi4',
    appId: '1:811849908533:android:0487e2735efb5179a88c7c',
    messagingSenderId: '811849908533',
    projectId: 'imageupload-cb863',
    storageBucket: 'imageupload-cb863.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj4_u3T8cVJB5TFVoAArQXHGPDbUPIW_c',
    appId: '1:811849908533:ios:f7847bebfbc34bffa88c7c',
    messagingSenderId: '811849908533',
    projectId: 'imageupload-cb863',
    storageBucket: 'imageupload-cb863.appspot.com',
    iosBundleId: 'com.example.imagepick',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj4_u3T8cVJB5TFVoAArQXHGPDbUPIW_c',
    appId: '1:811849908533:ios:f7847bebfbc34bffa88c7c',
    messagingSenderId: '811849908533',
    projectId: 'imageupload-cb863',
    storageBucket: 'imageupload-cb863.appspot.com',
    iosBundleId: 'com.example.imagepick',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHvak7fv75OzfdvYGAGfW4K8nXFkP-240',
    appId: '1:811849908533:web:8668ab61c2d55ac9a88c7c',
    messagingSenderId: '811849908533',
    projectId: 'imageupload-cb863',
    authDomain: 'imageupload-cb863.firebaseapp.com',
    storageBucket: 'imageupload-cb863.appspot.com',
    measurementId: 'G-WQRSYNSM07',
  );
}
